version: '2'
services:
  web:
    build: .
    image: mateuschmitz/php-phalcon:apache-7.0
    container_name: class-prediction-web
    hostname: class-prediction-web
    working_dir: /app
    depends_on:
      - mysql
    environment:
      - APPLICATION_ENV=development
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh
      - ./docs/apache/vhost:/etc/apache2/sites-available/000-default.conf

  mysql:
    image: mysql/mysql-server:5.6
    container_name: class-prediction-mysql
    hostname: class-prediction-mysql
    volumes:
      - ./docs/sql:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime
      - ./docs/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=102030
      - MYSQL_DATABASE=classprediction
      - MYSQL_USER=classprediction
      - MYSQL_PASSWORD=classprediction
      - MYSQL_ROOT_HOST=%
      # - MYSQL_HOST=%

  composer:
    image: composer/composer
    network_mode: host
    command: install --ignore-platform-reqs --prefer-dist -o
    volumes:
      - ~/.ssh:/root/.ssh
      - ./:/app

networks:
  default:
    external:
      name: dev